services:
  # База данных
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=get_proxy_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

  # Брокер
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://admin:secret@db:5432/get_proxy_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - db
      - redis
  # Бэкенд
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:secret@db:5432/get_proxy_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # Фронтенд
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - web
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data: