# Generated by Django 6.0.5 on 2026-05-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='host',
            field=models.GenericIPAddressField(),
        ),
    ]
